- styles.css
<ul># What’s been improved:
<li>The form has a centered, white background with a slight shadow to make it pop.
<li>Larger and more readable input fields.
<li>The submit button is now more visible and responsive with hover effects.
</ul>
> Fix the feedback form

- styles.css
The navbar is display all items in one row, with "Waste Management" positioned before or next to the other menu items.
The "Our Features" section is centrally aligned, with its content neatly centered in the available space.
> Issue #4 - Improve Navbar and Center 'Our Features' Section

- CODE_OF_CONDUCT.md
- LICENSE
- README.md
This pull request adds the following essential files to the project:
- **README.md**: Provides an overview of the Waste Management project, including a detailed description, technology stack, contribution guidelines, and color palette.
- **CODE_OF_CONDUCT.md**: Outlines the expected behavior for contributors and promotes a positive community.
- **LICENSE**: Specifies the terms under which the project is licensed (MIT License).
Closes #1
> Add README.md, CODE_OF_CONDUCT.md, and LICENSE files

- index.html
- styles.css
Changed the font of the website and made UI of Hero section better.
Resolves #5
> Hero section changed

- index.html
- styles.css
I created an interactive feature showcasing the types of biodegradable and non-biodegradable waste. Adding basic information about waste classification can help users understand the different types of waste and how to manage them effectively.
> Classification of waste Features

- index.html
- styles.css
Sucessfully added relevant design for the subscribe button and aslo addes a communit block at the end
Before 
After
> added design to the subscribe button and  added community section #38

- index.html
- script.js
- styles.css
Resolved #37 
After Changes : 
https://github.com/user-attachments/assets/b2988f24-2959-496f-b4ac-9a5b27b3921b
> Added a fixed navigation bar and scroll progress bar.

- index.html
- styles.css
modified the upload section and now it is looking more clean and good as compared to earlier
> changes done in the upload section

- .github/workflows/static.yml
- README.md
- styles.css
Use more consistent font sizes across the page. The text in the "Waste Management" link seems small compared to the rest of the navigation. Aim for uniformity in text size to improve readability.
> Typography

- carbon-footprint.html
This is the html file for creatin the carbon foot print feature.
> #78 Create carbon-footprint.html

- CARBON FOOTPRINT CALC/car.css
- CARBON FOOTPRINT CALC/car.html
- CARBON FOOTPRINT CALC/flight.css
- CARBON FOOTPRINT CALC/flights.html
- CARBON FOOTPRINT CALC/house.css
- CARBON FOOTPRINT CALC/house.html
- CARBON FOOTPRINT CALC/motorbike.css
- CARBON FOOTPRINT CALC/motorbike.html
- CARBON FOOTPRINT CALC/result.css
- CARBON FOOTPRINT CALC/results.html
- CARBON FOOTPRINT CALC/secondary.css
- CARBON FOOTPRINT CALC/secondary.html
- CARBON FOOTPRINT CALC/transport.css
- CARBON FOOTPRINT CALC/transport.html
- CARBON FOOTPRINT CALC/welcome.css
- CARBON FOOTPRINT CALC/welcome.html
- index.html
Closes: #78 
A carbon footprint is the total amount of greenhouse gases (GHGs) produced by an individual, organization, product, or service.
Note:- i had made the UI only , i will make it working in next pr. Looking forward to accept my isuue further.
- [✅ ] New feature (non-breaking change that adds functionality)
- [  ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [✅ ] Documentation update (Documentation content changed)
- [✅  ] My code follows the style guidelines of this project
- [✅  ] I have performed a self-review of my own code
- [ ✅] I have commented my code, particularly in hard-to-understand areas
- [ ✅ ] I have made corresponding changes to the documentation
- [✅  ] My changes generate no …
> added `Carbon footprint`

- styles.css
Closes: #(issue number)
Provide a brief description of what this pull request does and why it is needed.
Include any detailed information about the changes in this pull request.
If applicable, please attach screenshots of the changes made to the user interface.
Please provide any other information that is relevant to this pull request.
> #174 Update styles.css

- CONTRIBUTING.md
- README.md
Closes: #193
Created a file on how to contribute in the repo.  named CONTRIBUTING.md and also modified Readme.md
one new file 
changes in file named Readme.md
- [ *] Documentation update (Documentation content changed)
- [* ] My code follows the style guidelines of this project
- [ *] I have performed a self-review of my own code
- [ *] I have commented my code, particularly in hard-to-understand areas
- [* ] I have made corresponding changes to the documentation
- [* ] My changes generate no new warnings
- [ *] My changes do not break the current system and pass all existing test cases
- [* ] I have added tests that prove my fix is effective or that my feature works
- [ *] New and existing unit tests pass locally …
> Added requested file/Created CONTRIBUTING.md and changed readme.md accordingly "issue no-#193"

- ecotips.html
- index.html
- register.html
- styles.css
Closes: #243
This pull request resolves the issue where the header links were not functioning properly on the sign-in page.
Root Cause: The issue was caused by overlapping elements or missing event listeners that prevented the header links from being clickable. The header element was not behaving consistently on the sign-in page compared to other pages.
- [] New feature (non-breaking change that adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] Documentation update (Documentation content changed)
https://github.com/user-attachments/assets/1abdad32-2f26-4031-a6f9-ddba45c86a75
> Header Links Not Working on Sign-in Page #243

- community.html
- index.html
- register.html
- styles.css
Closes: #172 
The sign up page looks very blind where the header contains all the links that not take to the respective pages. But now the issue is solved and the continue with google option is also added, which enhance the user friendly platform to user.
Also for security the password has certain conditions like 8 words uppercase, lowercase and special characters.
The sign up page and login page looks very attractive and the user feels it very friendly
1. The header section contains many content which are removed .
2.  The footer section has also been added successfully.
- [  ] New feature (non-breaking change that adds functionality)
- [  ] Documentation update (Documentation content changed)
- [  ] My code follows …
> The Signup Page Enhancement

- index.html
Changed old twitter logo to X new logo
Kindly add hactoberfest-accepted , gssoc-extd level 2
> Changed old twitter logo to X new logo

- community.html
- index.html
- register.html
- styles.css
Closes: #171 
The Join Community section now has a button which takes the user to the new page where the user can find the details of the waste management team and social media links.
The waste management team needs a community support and the users wants to know who are the persons behind the projects . The like minded peoples can connect together through their social media links.
- [  ] New feature (non-breaking change that adds functionality)
-  [  ] Documentation update (Documentation content changed)
- [  ] My code follows the style guidelines of this project
- [  ] I have performed a self-review of my own code
- [  ] I have commented my code, particularly in hard-to-understand areas
- [  ] I have made …
> The Creation Of New Community Page

- index.html
- styles.css
Add Animated Buttons to Navbar for Improved User Experience #258
Closes: #258
https://github.com/user-attachments/assets/d1634dd3-e3ef-4a87-93ee-db31db99fc13
pplicable, please attach screenshots of the changes made to the user interface.
Please provide any other information that is relevant to this pull request.
> Add Animated Buttons to Navbar for Improved User Experience #258

- .vscode/settings.json
- index.html
- script.js
- styles.css
Responsiveness and dark mode is added
#266 (Its not responsive
Responsiveness ensures that a website adapts to various screen sizes and devices, such as desktops, tablets, and smartphones. With mobile usage continuing to grow, it’s essential for websites to provide a seamless experience across all platforms. A responsive site enhances user experience by eliminating the need for zooming or excessive scrolling, leading to higher engagement and lower bounce rates. It also boosts SEO performance, as search engines prioritize mobile-friendly websites.
Dark mode offers a darker color scheme with light text, which is becoming increasingly popular among users. It reduces eye strain, especially in low-light environments, making it more comfortable for longer use. Dark mode is also energy-efficient …
> Responsiveness and darkmode is added

- index.html
- register.html
- styles.css
Closes: #270
Provide a brief description of what this pull request does and why it is needed.
Include any detailed information about the changes in this pull request.
Please provide any other information that is relevant to this pull request.
> [Feature] Themed Redesign for Sign-Up Page #270

- index.html
- styles.css
> Making header more visually appealing
